### ISSUE TITLE
linkml-run-examples missing base prefix

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/mixs-6-2-release-candidate#186]

**Comment by turbomam** [comment]
> Traceback (most recent call last):
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml/utils/converter.py", line 175, in cli
    dumper.dump(obj, output, **outargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 154, in dump
    super().dump(element, to_file, schemaview=schemaview, fmt=fmt, prefix_map=prefix_map)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/dumper_root.py", line 19, in dump
    output_file.write(self.dumps(element, **_))
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 167, in dumps
    return self.as_rdf_graph(element, schemaview, prefix_map=prefix_map).\
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 59, in as_rdf_graph
    self.inject_triples(element, schemaview, g)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 132, in inject_triples
    v_node = self.inject_triples(v, schemaview, graph, slot.range)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 111, in inject_triples
    element_uri = self._as_uri(element_id, id_slot, schemaview)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 174, in _as_uri
    return schemaview.namespaces().uri_for(element_id)
  File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-xMtsyy1A-py3.9/lib/python3.9/site-packages/linkml_runtime/utils/namespaces.py", line 212, in uri_for
    raise ValueError(f"{TypedNode.yaml_loc(uri_or_curie)}Unknown CURIE prefix: {prefix}")
ValueError: File "MixsCompliantData-MimsSoil-example.yaml", line 11, col 16: Unknown CURIE prefix: @base
make: *** [/home/mark/gitrepos/mixs-envo-struct-knowl-extraction/project.Makefile:546: converted-data/MimsSoil-example.ttl] Error 1

**Comment by turbomam** [comment]
from `samp_name`, because I set `identifier` to `True`

**Comment by turbomam** [comment]
do I need to set the following in `linkml-convert`?

-c, --context TEXT              path to JSON-LD context file

**Comment by bartkl** [comment]
I am trying to convert some of my own test JSON data to JSON-LD as well, and I've stumbled on this very same problem. In this test data, I have an `id` slot with `identifier: True` as you mention, @turbomam , and removing that solves the issue.

But why is it a problem to set `identifier: True`? Does it have to do with the mapping LinkML does of the `id` slot to the `@id` keyword in JSON-LD?

Would be nice if the schema authoring wouldn't get in the way of the generator.

**Comment by turbomam** [comment]
Hi @bartkl 

I'd like to discuss this more with you, but this repo is essentially archived. Can we try to do you validation in microbiomedata/mixs?

**Comment by bartkl** [comment]
I'll post my question in Slack, since it's not an immediate issue that really needs resolving, but there's a few of these minor nuisances every now and then that I wish to understand (or hopefully contribute to solving)
